#!/usr/bin/python
import boto3
ec2client = boto3.client('ec2')
ec2=boto3.resource('ec2')
for i in ec2.instances.all():
    list1=i.block_device_mappings
    it=iter(list1)
    for j in it:
        vol=ec2.Volume(j['Ebs']['VolumeId'])
        if vol.volume_type=='standard':
           if i.state['Name']=='running':
              stopres=ec2client.stop_instances(InstanceIds=[i.id],DryRun=False)
              i.wait_until_stopped()
              snap=ec2.create_snapshot(VolumeId=j['Ebs']['VolumeId'],Description=vol.tags[0]['Value'])
              snap.wait_until_completed()
              newvol=ec2.create_volume(SnapshotId=snap.id,VolumeType='gp2',AvailabilityZone=vol.availability_zone,Size=vol.size)
           elif i.state['Name']=='stopped':
              snap1=ec2.create_snapshot(VolumeId=j['Ebs']['VolumeId'],Description=vol.tags[0]['Value'])
              snap1.wait_until_completed()
              newvol=ec2.create_volume(SnapshotId=snap1.id,VolumeType='gp2',AvailabilityZone=vol.availability_zone,Size=vol.size)
