#!/usr/bin/python
import boto3
ec2=boto3.resource('ec2')
for i in ec2.instances.all():
    if i.state.values()[1]=='running':
       print('{0} {1} {2}'.format(i.id, i.instance_type, i.private_ip_address))

