#!/usr/bin/python
import boto3
ec2=boto3.resource('ec2')
for i in ec2.instances.all():
    list1=i.block_device_mappings
    it=iter(list1)
    for j in it:
        list2=j.values()
        list3=list2[1].values()
        print('{0} {1} {2} {3}'.format(i.id, i.private_ip_address, list2[0], list3[2]))
