#!/usr/bin/python
import boto3
client = boto3.client('rds')
response=client.describe_db_instances()
def rdshandler(event,context):
    for i in response['DBInstances']:
        if event['action'] == 'on':
           res=client.start_db_instance(DBInstanceIdentifier=i['DBInstanceIdentifier'])
        elif event['action'] == 'off':
           res=client.stop_db_instance(DBInstanceIdentifier=i['DBInstanceIdentifier'])
    return 'Thanks, the function rdshandler has finished execution'

