#!/usr/bin/python
import boto3
ec2=boto3.resource('ec2')
for volume in ec2.volumes.all():
    snapshot = ec2.create_snapshot(
          Description='description',
          VolumeId=volume.id,
          DryRun=False,
)
