#!/usr/bin/python
import boto3
import sys
from botocore.exceptions import ClientError
action = sys.argv[1].upper()
client = boto3.client('rds')
response=client.describe_db_instances()
for i in response['DBInstances']:
    if action == 'ON':
       res=client.start_db_instance(DBInstanceIdentifier=i['DBInstanceIdentifier'])
    elif action == 'OFF':
       res=client.stop_db_instance(DBInstanceIdentifier=i['DBInstanceIdentifier'])

